version: '3.8'

services:
  # Backend (Node.js)
  backend:
    build:
      context: C:\Users\ehuss\OneDrive\Desktop\eventPlanner-back\eventplanner-backend
      dockerfile: Dockerfile
    container_name: eventplanner-backend
    ports:
      - "3000:3000"
    env_file:
      - C:\Users\ehuss\OneDrive\Desktop\eventPlanner-back\eventplanner-backend\.env
      # - C:\Users\ehuss\OneDrive\Desktop\eventPlanner-back\eventplanner-backend\.env
    networks:
      - eventplanner-network
    restart: unless-stopped

  # Frontend (Angular + Nginx)
  frontend:
    build:
      context: C:\Users\ehuss\OneDrive\Desktop\event front\eventplanner-frontend
      dockerfile: Dockerfile
    container_name: eventplanner-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - eventplanner-network
    restart: unless-stopped

# Network for container communication
networks:
  eventplanner-network:
    driver: bridge